package com.quizmaster.config;

import com.quizmaster.entity.*;
import com.quizmaster.repository.*;
import java.util.*;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class DataInitializer {
    @Bean CommandLineRunner seedData(TopicRepository topics, QuestionRepository questions) {
        return args -> {
            if (topics.count() > 0) return;
            Map<String, Topic> saved = new LinkedHashMap<>();
            for (String name : List.of("General Knowledge", "Science", "Technology", "History", "Geography", "Sports", "Movies", "Gaming")) saved.put(name, topics.save(new Topic(name)));
            seed(questions, saved.get("General Knowledge"), new String[][] {
                q("What is the capital of France?","Paris","Rome","Madrid","Berlin","A"), q("Which ocean is the largest?","Atlantic","Indian","Pacific","Arctic","C"), q("How many days are in a leap year?","364","365","366","367","C"), q("What is the currency of Japan?","Won","Yen","Yuan","Rupee","B"), q("Which animal is known as the king of the jungle?","Tiger","Lion","Elephant","Bear","B"), q("Which planet is closest to the Sun?","Venus","Earth","Mercury","Mars","C"), q("What color do red and blue make?","Green","Purple","Orange","Yellow","B"), q("How many continents are there?","Five","Six","Seven","Eight","C"), q("Who painted the Mona Lisa?","Van Gogh","Picasso","Da Vinci","Monet","C"), q("What is the tallest mammal?","Elephant","Giraffe","Horse","Camel","B") });
            seed(questions, saved.get("Science"), new String[][] {
                q("What is H2O commonly known as?","Salt","Water","Oxygen","Hydrogen","B"), q("Which gas do plants absorb from the air?","Oxygen","Nitrogen","Carbon dioxide","Helium","C"), q("What is the center of an atom called?","Electron","Nucleus","Proton","Orbit","B"), q("Which organ pumps blood around the body?","Lungs","Brain","Heart","Liver","C"), q("What force keeps planets in orbit?","Magnetism","Gravity","Friction","Electricity","B"), q("What is the chemical symbol for gold?","Go","Gd","Au","Ag","C"), q("Which blood cells fight infection?","Red cells","White cells","Platelets","Plasma","B"), q("What is the hardest natural substance?","Iron","Diamond","Quartz","Granite","B"), q("Which planet is called the Red Planet?","Mars","Jupiter","Saturn","Venus","A"), q("What type of animal is a frog?","Reptile","Mammal","Amphibian","Fish","C") });
            seed(questions, saved.get("Technology"), new String[][] {
                q("What does CPU stand for?","Central Process Unit","Central Processing Unit","Computer Personal Unit","Core Processing Utility","B"), q("Which language runs in a web browser?","Java","C++","JavaScript","Python","C"), q("What does HTML stand for?","HyperText Markup Language","HighText Machine Language","Home Tool Markup Language","Hyperlink Text Mode Language","A"), q("Which company developed Windows?","Apple","Google","Microsoft","IBM","C"), q("What does URL stand for?","Uniform Resource Locator","Universal Reference Link","User Resource Location","Unified Routing Link","A"), q("Which device stores data permanently?","RAM","CPU cache","SSD","GPU","C"), q("What is the binary value of decimal 2?","1","10","11","100","B"), q("Which protocol is used for secure websites?","HTTP","FTP","HTTPS","SMTP","C"), q("What does RAM stand for?","Random Access Memory","Read Access Module","Rapid Active Memory","Remote Array Memory","A"), q("Which is an open-source operating system?","Windows","macOS","Linux","iOS","C") });
            seed(questions, saved.get("History"), new String[][] {
                q("Who was the first President of the United States?","Abraham Lincoln","George Washington","Thomas Jefferson","John Adams","B"), q("The pyramids of Giza are in which country?","Mexico","Greece","Egypt","Italy","C"), q("Who wrote the Declaration of Independence?","Thomas Jefferson","Benjamin Franklin","George Washington","James Madison","A"), q("Which war ended in 1945?","World War I","World War II","Korean War","Vietnam War","B"), q("The Roman Empire was centered on which city?","Athens","Rome","Paris","Carthage","B"), q("Who discovered penicillin?","Isaac Newton","Alexander Fleming","Louis Pasteur","Marie Curie","B"), q("Which civilization built Machu Picchu?","Maya","Aztec","Inca","Roman","C"), q("Who was known as the Maid of Orleans?","Cleopatra","Joan of Arc","Queen Victoria","Marie Antoinette","B"), q("The Magna Carta was signed in which country?","France","England","Spain","Germany","B"), q("Who was India's first Prime Minister?","Mahatma Gandhi","Jawaharlal Nehru","Sardar Patel","Indira Gandhi","B") });
            seed(questions, saved.get("Geography"), new String[][] {
                q("What is the longest river in South America?","Amazon","Nile","Yangtze","Mississippi","A"), q("Mount Everest is part of which mountain range?","Andes","Alps","Himalayas","Rockies","C"), q("Which country has the largest population in Africa?","Nigeria","Egypt","South Africa","Kenya","A"), q("What is the capital of Australia?","Sydney","Melbourne","Canberra","Perth","C"), q("Which desert is the largest hot desert?","Gobi","Sahara","Kalahari","Atacama","B"), q("Which country is shaped like a boot?","Greece","Portugal","Italy","Chile","C"), q("What is the smallest continent?","Europe","Australia","Antarctica","South America","B"), q("Which sea separates Europe and Africa?","Black Sea","Red Sea","Mediterranean Sea","Arabian Sea","C"), q("What is the capital of Canada?","Toronto","Vancouver","Ottawa","Montreal","C"), q("Which country contains the city of Kyoto?","China","Japan","South Korea","Thailand","B") });
            seed(questions, saved.get("Sports"), new String[][] {
                q("How many players are on a soccer team on the field?","9","10","11","12","C"), q("Which sport uses a shuttlecock?","Tennis","Badminton","Squash","Table tennis","B"), q("In which sport is a home run scored?","Cricket","Baseball","Basketball","Golf","B"), q("How many rings are on the Olympic flag?","4","5","6","7","B"), q("Which country hosted the 2016 Summer Olympics?","China","Brazil","Japan","United Kingdom","B"), q("What is the maximum score from one dart?","20","50","60","100","C"), q("Which sport is associated with Wimbledon?","Golf","Tennis","Cricket","Rugby","B"), q("A marathon is approximately how many kilometers?","21","30","42","50","C"), q("Which sport uses a pommel horse?","Gymnastics","Equestrian","Fencing","Diving","A"), q("How many points is a touchdown worth in American football?","3","5","6","7","C") });
            seed(questions, saved.get("Movies"), new String[][] {
                q("Who directed Titanic?","James Cameron","Steven Spielberg","Christopher Nolan","Ridley Scott","A"), q("Which film features the character Darth Vader?","Star Trek","Star Wars","The Matrix","Avatar","B"), q("Which animated film has the song Let It Go?","Moana","Frozen","Tangled","Coco","B"), q("Who played Iron Man in the Marvel films?","Chris Evans","Robert Downey Jr.","Chris Hemsworth","Mark Ruffalo","B"), q("Which movie won Best Picture at the 2020 Oscars?","1917","Joker","Parasite","Ford v Ferrari","C"), q("What is the fictional African nation in Black Panther?","Zamunda","Wakanda","Genovia","Latveria","B"), q("Which film series features Hobbits?","Harry Potter","The Lord of the Rings","Narnia","Star Wars","B"), q("Who played the title role in Forrest Gump?","Tom Hanks","Robin Williams","Matt Damon","Brad Pitt","A"), q("Pixar's first feature film was?","Toy Story","Cars","Finding Nemo","Monsters Inc.","A"), q("Which movie features a sinking ocean liner?","Titanic","Jaws","The Poseidon Adventure","Life of Pi","A") });
            seed(questions, saved.get("Gaming"), new String[][] {
                q("Which company created the Mario franchise?","Sega","Nintendo","Sony","Microsoft","B"), q("What color is Sonic the Hedgehog?","Red","Blue","Green","Yellow","B"), q("Which game features blocks called Tetriminos?","Minecraft","Tetris","Roblox","Fortnite","B"), q("What is the main resource mined in Minecraft?","Coins","Blocks","Stars","Cards","B"), q("Which console family is made by Sony?","Xbox","PlayStation","Switch","Dreamcast","B"), q("In chess, which piece moves in an L shape?","Bishop","Rook","Knight","Queen","C"), q("Which game series includes Pikachu?","Digimon","Pokemon","Zelda","Final Fantasy","B"), q("What genre is FIFA primarily?","Racing","Sports","Puzzle","Strategy","B"), q("Which game features the character Link?","Mario","The Legend of Zelda","Sonic","Halo","B"), q("What does NPC mean in gaming?","New Player Character","Non-Player Character","Next Play Control","Network Player Code","B") });
        };
    }
    private static String[] q(String text, String a, String b, String c, String d, String answer) { return new String[]{text, a, b, c, d, answer}; }
    private static void seed(QuestionRepository repository, Topic topic, String[][] rows) { for (String[] r : rows) repository.save(new Question(topic, r[0], r[1], r[2], r[3], r[4], r[5])); }
}
